name = "EpsteinLib"
uuid = "a842d94e-5710-4e9e-8aa7-655017b7ad80"
license = "AGPL-3.0-only"
authors = ["David Gomez-Castro <david@gomezcastro.xyz>", "Jonathan K. Busse <jonathan@jbusse.de>"]
version = "0.5.0"

[deps]
Epsteinlib_jll = "4ec54591-1743-56ec-8704-f258a6d96b61"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Epsteinlib_jll = "0.5.0"
julia = "1"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SpecialFunctions", "JuliaFormatter"]
