name = "EpsteinZetaFunction"
uuid = "a842d94e-5710-4e9e-8aa7-655017b7ad80"
version = "0.1.0"
authors = ["David Gomez-Castro <david@gomezcastro.xyz>"]

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Libdl = "1.11.0"
LinearAlgebra = ">=1.11.0"
SpecialFunctions = "2.6.1"
Test = "1.11.0"
